[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn thecrust.wsgi --bind 0.0.0.0:$PORT --workers 2"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
